CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "organizer_id" integer NOT NULL,
  "location" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "invitations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending',
  "invited_at" timestamp DEFAULT (now()),
  "comment" varchar
);

CREATE TABLE "reminders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "remind_at" timestamp NOT NULL,
  "type" varchar NOT NULL DEFAULT 'email',
  "is_sent" boolean NOT NULL DEFAULT false
);

COMMENT ON COLUMN "invitations"."status" IS 'pending, accepted, declined';

ALTER TABLE "events" ADD FOREIGN KEY ("organizer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invitations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invitations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reminders" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reminders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
